min_particles: 500
max_particles: 2000
kld_err: 0.05
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.1
odom_alpha4: 0.1
odom_alpha5: 0.1
laser_lambda_short: 0.1
laser_sigma_hit: 0.2
laser_z_hit: 0.9
laser_z_max: 0.05
laser_z_rand: 0.05
